### PR TITLE
add Match.Maybe

### PR DESCRIPTION
**Pull request by Hongbo-Miao**
Refer to [API](https://docs.meteor.com/api/check.html#matchpatterns)

### CODE REVIEW

**Comment by barbatus** [comment]
I think it's been added to 1.3, so can you please move it to 1.3/packages/check.d.ts?

**Comment by Hongbo-Miao** [comment]
@barbatus done!

**Comment by barbatus** [comment]
so i don't see 1.3/packages/check.d.ts

**Comment by Hongbo-Miao** [comment]
@barbatus hmm.. is this time correct?

**Pull request merged**
