### PR TITLE
Add Meteor.isDevelopment and Mongo.Collection._dropIndex

### PR DESCRIPTION
**Pull request by exKAZUu**
- Meteor.isDevelopment  
https://docs.meteor.com/api/core.html#Meteor-isDevelopment
- Mongo.Collection._dropIndex  
https://github.com/meteor/meteor/blob/05f65f9b2180efa6293289393e4fa0e3b1efa3a9/packages/mongo/collection.js#L687-L692

### CODE REVIEW

**Comment by barbatus** [comment]
Thanks! Please read https://github.com/meteor-typings/meteor#contribution

**Comment by exKAZUu** [comment]
Sorry, I missed that section. I will re-create PR.

**Comment by exKAZUu** [comment]
@barbatus `Meteor.isDevelopment` seems to be introduced since Meteor 1.3. How can I add such a 1.3-specific definition?

**Comment by barbatus** [comment]
if it does matter, add it to 1.3/packages/meteor.d.ts

**Comment by exKAZUu** [comment]
I see. Thanks!

**Pull request closed without merging**
