### PR TITLE
meteor 1.4

### PR DESCRIPTION
**Pull request by dagatsoin**
Feel free to list any thing you want to include in. Even if it is not documented (for example I use Meteor.loginWithToken)

- [x] Accounts.onLogout()
- [x] Meteor._debug()
- [x] Meteor.loginWithToken()
- [x] bump to TS 2.1.5

### CODE REVIEW

**Comment by dagatsoin** [comment]
@barbatus I end with plenty of duplicate module declarations. For example:

```
declare module DDP {
  interface DDPStatic {
    subscribe(name: string, ...rest: any[]): Meteor.SubscriptionHandle;
    call(method: string, ...parameters: any[]): void;
    apply(method: string, ...parameters: any[]): void;
    methods(IMeteorMethodsDictionary: any): any;
    status(): DDPStatus;
    reconnect(): void;
    disconnect(): void;
    onReconnect(): void;
  }

  function _allSubscriptionsReady(): boolean;

  type Status = "connected" | "connecting" | "failed" | "waiting" | "offline";

  interface DDPStatus {
    connected: boolean;
    status: Status;
    retryCount: number;
    retryTime?: number;
    reason?: string;
  }

  function connect(url: string): DDPStatic;
}

declare module DDPCommon {
  interface MethodInvocation {
    new(options: {}): MethodInvocation;

    unblock(): void;

    setUserId(userId: number): void;
  }
}

declare module "meteor/ddp" {
  module DDP {
    interface DDPStatic {
      subscribe(name: string, ...rest: any[]): Meteor.SubscriptionHandle;
      call(method: string, ...parameters: any[]): void;
      apply(method: string, ...parameters: any[]): void;
      methods(IMeteorMethodsDictionary: any): any;
      status(): DDPStatus;
      reconnect(): void;
      disconnect(): void;
      onReconnect(): void;
    }

    function _allSubscriptionsReady(): boolean;

    type Status = "connected" | "connecting" | "failed" | "waiting" | "offline";

    interface DDPStatus {
      connected: boolean;
      status: Status;
      retryCount: number;
      retryTime?: number;
      reason?: string;
    }

    function connect(url: string): DDPStatic;
  }

  module DDPCommon {
    interface MethodInvocation {
      new(options: {}): MethodInvocation;

      unblock(): void;

      setUserId(userId: number): void;
    }
  }
}
```

How could I avoid this?

**Comment by barbatus** [comment]
Which ones are duplicated? If you mean `DDPCommon`, it's not duplicated.
The first one is an ambient module existed for 1.2 (but they are yet supported in 1.3), another one is a part of the regular module, the ones that should be imported and appeared in 1.3.

**Comment by dagatsoin** [comment]
Yes, my example is not relevant. I reformulate.

If I take the master branch and compile. I end with a 1.2/main.d.ts and 1.2/browser.d.ts having some duplicate. Eg : [here](https://github.com/meteor-typings/meteor/blob/master/1.2/browser.d.ts#L72) and [here](https://github.com/meteor-typings/meteor/blob/master/1.2/main.d.ts#L72) 

And it seems not normal because
```
interface Header {
  [id: string]: string;
}
```
is located in `packages/accounts-base_browser.d.ts`

**Comment by dagatsoin** [comment]
At the compile, here is the relevant error for the example above: `(76,3): error TS2374: Duplicate string index signature.` and I got plenty like this one.

**Comment by dagatsoin** [comment]
I fix this by excluding `*_browser.d.ts` files when concataining `*_main.d.ts` files and vis versa.
https://github.com/meteor-typings/meteor/pull/30/commits/cbb2f8410ea75448b58020ceaa9c24b3039a8e1a#diff-b9e12334e9eafd8341a6107dd98510c9R13

**Comment by dagatsoin** [comment]
I have now some missing module. I am checking this.

**Comment by barbatus** [comment]
How do you install Meteor typings so that you have both `browser.d.ts` and `main.d.ts` applied?
As I remember  initially i wanted to support that separation main/browser since the `typings` tool could install them separately by default. But then they made it optional, which means it's gonna work only if user puts [this](https://github.com/meteor-typings/meteor/blob/master/typings.json#L9) into the `typings.json`. So I decided to postpone it.
But then suddenly typescript got new feature to install and use typings via NPMs and everybody stated using it. And `package.json` has only one field to reference typings so far:  [`typings`](https://github.com/meteor-typings/meteor/blob/master/package.json#L11).
I think it's still easy to fix by changing gulp rules to ignore `*_browser.d.ts` for the main and vice versa. But i don't think we need `browser.d.ts` at all now since as I can see general strategy that those who create typings follow is to keep typings simple having only one `main.d.ts`.

**Comment by dagatsoin** [comment]
Ok I fixed the separation. Now:
- main.d.ts contains the server side api and the browser api. So the test now passes.
- browser.d.ts contains only client side api.

Concerning npm @types, the main.d.ts could be used simply as this I think. So you have both a solution for using Typings and Npm. We just have to get a look to the @types guidelines and publish on npm.

**Comment by barbatus** [comment]
yes good point to move to it to @types. Probably makes sense even to move all repos in this organization to @types. But from other side, it's still convenient to have all Meteor typings in one place.

**Comment by barbatus** [comment]
So did you finish this PR?

**Comment by dagatsoin** [comment]
Yes, it is good for me.

**Pull request merged**
