### PR TITLE
Add Accounts.urls property with URLS interface

### PR DESCRIPTION
**Pull request by ijager**
URLS interface holds functions that return urls for resetPassword,
verifyEmail and enrollAccount. Using these typings these functions can be
overridden to provide custom urls.

Example:

````  
// override enroll url
Accounts.urls.enrollAccount = function(token: string) {
  return Meteor.absoluteUrl('enroll-account/' + token);
}
````

### CODE REVIEW

**Comment by barbatus** [comment]
This is good. Can you please add these changes to https://github.com/meteor-typings/meteor/blob/master/1.2/packages/accounts-base.d.ts, which is a primary location of the package typings. `main.d.ts` and other such files are built out of them.

**Comment by ijager** [comment]
Okay, I see the Contribution guidelines now :) . I don't understand on what basis accounts-base.d.ts and accounts-base_main.d.ts are split up though.

**Comment by barbatus** [comment]
Like in NPM, `main` means server environment, `browser` - client environment.
So, accounts-base_main.d.ts defines API available on the server, accounts-base_browser.d.ts  - on the client. Same is true for other files.

**Comment by ijager** [comment]
Thanks, I got it.  The PR has been updated.

**Pull request merged**
